### ISSUE TITLE
์Not working

### ISSUE THREAD

**Issue by watchakorn-18k** [AdvMaple/biliint.com-bilibili.tv_subtitle_download_plugin#5]
It doesn't show to download.

link I will load is https://www.bilibili.tv/en/play/1013552
![image](https://user-images.githubusercontent.com/74919942/142465194-56e85c20-303e-44c9-ad1f-2c8efcd9171a.png)

**Comment by AdvMaple** [comment]
My Internet is down at the moment. I will have to wait about 1h30.
I already know where is that bug.
Sorry for the inconveniences.

**Comment by watchakorn-18k** [comment]
No problem i can wait

**Comment by AdvMaple** [comment]
![image](https://user-images.githubusercontent.com/46006210/142474260-d4f491ab-5fb4-40c7-b00f-d17d7c654358.png)
It should be working now. Just click update and it will pull the latest code.

**Comment by taiwinner** [comment]
> ![hình ảnh](https://user-images.githubusercontent.com/46006210/142474260-d4f491ab-5fb4-40c7-b00f-d17d7c654358.png) Nó sẽ hoạt động ngay bây giờ. Chỉ cần nhấp vào cập nhật và nó sẽ kéo mã mới nhất.

i tried new update. but it still doesn't seem to work.

**Comment by taiwinner** [comment]
> ![image](https://user-images.githubusercontent.com/46006210/142474260-d4f491ab-5fb4-40c7-b00f-d17d7c654358.png) It should be working now. Just click update and it will pull the latest code.
i tried new update. but it still doesn't seem to work.

**Comment by AdvMaple** [comment]
Can you show me your script version, it should be 0.5.4

**Comment by AdvMaple** [comment]
![image](https://user-images.githubusercontent.com/46006210/142571377-e13e5c6e-8645-4dca-9335-946cde9ae23c.png)
With Ep7 is premium, so it's won't be able to get download link. But everything should be OK.

**Comment by watchakorn-18k** [comment]
thank you for your hard work program now works normally.

**Comment by watchakorn-18k** [comment]
![image](https://user-images.githubusercontent.com/74919942/142613201-a74e2232-3bf0-4b88-b601-882f1249ab3a.png)
![image](https://user-images.githubusercontent.com/74919942/142613111-4c63d5c1-4a36-48a5-b335-2080c1f6fd0b.png)
![image](https://user-images.githubusercontent.com/74919942/142613169-f3f81f72-0bec-40b3-87fe-82d897b94549.png)

 I modified UI a bit, don't know if I can pull requests to your repo.

**Comment by AdvMaple** [comment]
> 
> ![image](https://user-images.githubusercontent.com/74919942/142613201-a74e2232-3bf0-4b88-b601-882f1249ab3a.png)
> ![image](https://user-images.githubusercontent.com/74919942/142613111-4c63d5c1-4a36-48a5-b335-2080c1f6fd0b.png)
> ![image](https://user-images.githubusercontent.com/74919942/142613169-f3f81f72-0bec-40b3-87fe-82d897b94549.png)
> 
>  I modified UI a bit, don't know if I can pull requests to your repo.

Beautifully done. Just open a pull request, I will review it.

**Comment by Ciara-Aa** [comment]
I updated to the latest version but it doesn't work
![Uploading IMG_20211120_091038.jpg…]()

**Comment by Ciara-Aa** [comment]
I updated to the latest version but it doesn't work
![IMG_20211120_091038](https://user-images.githubusercontent.com/64529639/142710867-6a86f262-1209-49a0-8bdb-b5c8ca0fc07a.jpg)
