### ISSUE TITLE
The plugin will only work when switching to an English web page

### ISSUE THREAD

**Issue by plan291037** [AdvMaple/biliint.com-bilibili.tv_subtitle_download_plugin#8]
The plugin will only work when switching to an English web page. I use Thai language, but it's not working. I have no problem with this, just let you know. Thanks 👍 💯

**Comment by AdvMaple** [comment]
Yeah, it has problem on Vietnamese site also. It's caused by the regex I'm using. I would like to fix this and find a more elegant way to name the link.
Or I can just make it "1" "2" "3" "4" "5".

**Comment by THEBEST5555** [comment]
I have tried changing the web page to English. But I can't use the plugin.

**Comment by watchakorn-18k** [comment]
> I have tried changing the web page to English. But I can't use the plugin.

it works normally I'm not sure if you are using Chome browser ?
Or have you tried installing the latest version that Mr. AdvMaple has updated?
![image](https://user-images.githubusercontent.com/74919942/142737414-3cf913f7-75f5-4716-872c-ece3c4f767f2.png)

**Comment by THEBEST5555** [comment]
![image](https://user-images.githubusercontent.com/94337203/142737576-da1af877-81f6-43f2-9f83-c1041ebdfa2f.png)
i update it

**Comment by THEBEST5555** [comment]
I can use it now. My ad blocker seems to block javascript.

**Comment by THEBEST5555** [comment]
now it works. But I have to block javascript on BiliBili in order for the script to work which makes it not possible to watch the video either.

**Comment by AdvMaple** [comment]
> Now it works But I have to block javascript on BiliBili for the script to work. This makes it impossible to watch videos and do other things as well.

You don't have to block JS on Bilibili. Can you try running the script alone in a separate environment. This is probably caused by others plugin.

**Comment by THEBEST5555** [comment]
https://user-images.githubusercontent.com/94337203/142740539-28910717-c28f-44f2-ac6f-691f87216c59.mp4

**Comment by AdvMaple** [comment]
I will take a look at this.
