### ISSUE TITLE
I can't see the numbers

### ISSUE THREAD

**Issue by dantruong2312** [AdvMaple/biliint.com-bilibili.tv_subtitle_download_plugin#9]
[``](https://drive.google.com/file/d/14xr9nyCWqWKisP6yokBIAqCi9ddpjH2V/view?usp=sharing)
 i changed to eng language but I coudn't see the number or anything to click download so i recorded it, please check and tell me if i do anything wrong, thank you and sorry for my bad english   vì tui là ng việt

**Comment by AdvMaple** [comment]
> [``](https://drive.google.com/file/d/14xr9nyCWqWKisP6yokBIAqCi9ddpjH2V/view?usp=sharing) i changed to eng language but I coudn't see the number or anything to click download so i recorded it, please check and tell me if i do anything wrong, thank you and sorry for my bad english vì tui là ng việt

Bạn lên facebook này nhắn tin với page, mình sẽ hỗ trợ bằng teamview hoặc ultraview luôn https://www.facebook.com/AnimeTVN.tv

**Comment by dantruong2312** [comment]
ok ad
